services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: 2gb

  test-runner:
    image: node:18
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - selenium
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y netcat-openbsd &&
        echo '[INFO] ⏳ Waiting for Selenium to be ready on port 4444...' &&
        until nc -z selenium 4444; do sleep 1; done &&
        echo '[INFO] ✅ Selenium is up, running tests...' &&
        npm install &&
        node test.js
      "
